repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.11.4"
    hooks:
      - id: ruff
        pass_filenames: true
        entry: bash -c 'ruff check --fix --show-fixes --output-format=${RUFF_OUTPUT_FORMAT:-full} --ignore F401,F811,F823,F841,G004,UP028,E501,SIM108,E402,SIM118,E741,UP006,E711,SIM117,B028,E722,SIM102,SIM116,B005,SIM105,SIM103,SIM110,SIM201,E712,B018,B011,B904,SIM115,B023,SIM212,B006,SIM211,SIM210,B006,E721,B026,B020,G003,SIM113 "$@"'
      - id: ruff-format