tokenizer: null
server_url: null
model_name: null
scoring_prompt: Score the following response from 1 - 5.
num_samples: 4
sc_mode: mean
api_key: null
timeout: 5
temperature: 1.0
initial_concurrency: 50
min_concurrency: 5
max_concurrency: 200
default_score: 0.001
max_retries: 4
max_tokens: 16
min_score: 0
max_score: 5
apply_chat_template: False