defaults:
  - gsm8k_base

data:
  train_batch_size: 1024

actor_rollout_ref:
  model:
    use_remove_padding: False
  actor:
    ppo_mini_batch_size: 256
    ppo_micro_batch_size_per_gpu: 4
    use_kl_loss: False
  rollout:
    log_prob_micro_batch_size_per_gpu: 16

critic:
  model:
    use_remove_padding: False
  ppo_micro_batch_size_per_gpu: 4

trainer:
  n_gpus_per_node: 8
  val_before_train: False
  save_freq: -1
  total_training_steps: 1 