defaults:
  - gsm8k_base

data:
  train_batch_size: 8

actor_rollout_ref:
  model:
    use_remove_padding: True
  actor:
    ppo_mini_batch_size: 4
    ppo_micro_batch_size_per_gpu: 2
    use_kl_loss: False
  rollout:
    log_prob_micro_batch_size_per_gpu: 2
    gpu_memory_utilization: 0.6

critic:
  model:
    use_remove_padding: True
  ppo_micro_batch_size_per_gpu: 2

trainer:
  n_gpus_per_node: 2
  save_freq: 2
  resume_mode: disable
  total_training_steps: 2 