name: cpu

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
    paths:
      - "**/*.py"
      - .github/workflows/cpu_test.yml
  pull_request:
    branches:
      - main
    paths:
      - "**/*.py"
      - .github/workflows/cpu_test.yml

jobs:
  ray:
    runs-on: [self-hosted, gpu]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
            fetch-depth: 0
      - name: Install the current repository
        run: |
          pip install -e .[test]
      - name: Running dataset tests
        run: |
          git clone --depth 1 https://github.com/eric-haibin-lin/verl-data ~/
          pytest -s -x tests/verl
