name: e2e_dapo

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  pull_request:
    branches:
      - main
      - v0.2.x
    paths:
      - "**/*.py"
      - "verl/trainer/config/*.yaml"
      - .github/workflows/e2e_dapo.yml
      - "tests/e2e/*dapo.sh"
      - "!verl/trainer/main_ppo.py"
      - "!verl/trainer/fsdp_sft_trainer.py"
      - "!verl/trainer/config/ppo_megatron_trainer.yaml"
      - "!verl/workers/**/megatron_*.py"


# Declare permissions just read content.
permissions:
  contents: read

jobs:
  e2e_dapo_qwen:
    runs-on: [L20x2]
    timeout-minutes: 40 # Increase this timeout value as needed
    env:
      HTTP_PROXY: ${{ secrets.PROXY_HTTP }}
      HTTPS_PROXY: ${{ secrets.PROXY_HTTPS }}
      NO_PROXY: "localhost,127.0.0.1"
      VERL_HOME: "/github/home/verl"
    container:
      image: verlai/verl:vemlp-th2.4.0-cu124-vllm0.6.3-ray2.10-te1.7-v0.0.3
      options: --gpus "\"device=${CUDA_VISIBLE_DEVICES}\"" --shm-size=10g
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
            fetch-depth: 0
      - name: Install the current repository
        run: |
          pip3 install -e .[test,gpu]
      - name: Prepare DAPO-Math & GSM8K dataset
        run: |
          ray stop --force
          bash recipe/dapo/prepare_dapo_data.sh
          python3 examples/data_preprocess/gsm8k.py
      - name: Running the E2E test with the DAPO algorithm and data
        run: | 
          ray stop --force
          bash tests/e2e/run_dapo_qwen.sh