name: e2e_dapo

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  pull_request:
    branches:
      - main
      - v0.2.x
    paths:
      - "**/*.py"
      # Home
      - "recipe/dapo/src"
      - "recipe/dapo/prepare_dapo_data.sh"
      # Entrypoints
      - ".github/workflows/e2e_dapo.yml"
      - "tests/e2e/run_dapo.sh"
      - "!examples"
      - "!verl/trainer/main_*.py"
      - "!verl/trainer/fsdp_sft_trainer.py"
      # Megatron
      - "!verl/workers/**/megatron_*.py"


# Declare permissions just read content.
permissions:
  contents: read

jobs:
  e2e_dapo:
    runs-on: [L20x8]
    timeout-minutes: 40 # Increase this timeout value as needed
    env:
      HTTP_PROXY: ${{ secrets.PROXY_HTTP }}
      HTTPS_PROXY: ${{ secrets.PROXY_HTTPS }}
      NO_PROXY: "localhost,127.0.0.1"
      VERL_HOME: "/github/home/verl"
    container:
      image: verlai/verl:ngc-th2.6.0-cu126-vllm0.8.2-mcore0.11.0
      options: --gpus all --shm-size=10g
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
            fetch-depth: 0
      - name: Install the current repository
        run: |
          pip3 install -e .[test,gpu]
      - name: Prepare DAPO-Math & GSM8K dataset
        run: |
          ray stop --force
          bash recipe/dapo/prepare_dapo_data.sh
      - name: Running the E2E test with the DAPO algorithm and data
        run: | 
          ray stop --force
          bash tests/e2e/run_dapo.sh