name: e2e_grpo_gsm8k

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  pull_request:
    branches:
      - main
    paths:
      - "**/*.py"
      - "verl/trainer/config/*.yaml"
      - .github/workflows/e2e_grpo_gsm8k.yml
      - "tests/e2e/*.sh"
      - "!verl/trainer/fsdp_sft_trainer.py"
      - "!recipe/**"
      - "!verl/trainer/config/ppo_megatron_trainer.yaml"
      - "!verl/workers/**/megatron_*.py"

# Cancel jobs on the same ref if a new one is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

# Declare permissions just read content.
permissions: 
  contents: read

jobs:
  e2e_grpo_gsm8k_qwen:
    runs-on: [L20x2]
    timeout-minutes: 40 # Increase this timeout value as needed
    env:
      HTTP_PROXY: ${{ secrets.PROXY_HTTP }}
      HTTPS_PROXY: ${{ secrets.PROXY_HTTPS }}
      NO_PROXY: "localhost,127.0.0.1"
      VLLM_ATTENTION_BACKEND: XFORMERS # TODO: Remove after update vllm in container
    container:
      image: whatcanyousee/verl:vemlp-th2.4.0-cu124-vllm0.6.3-ray2.10-te2.0-megatron0.11.0-v0.0.6
      options: --gpus 2 --shm-size=10g
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
            fetch-depth: 0
      - name: Install the current repository
        run: |
          pip3 install .[test]
      - name: Prepare gsm8k dataset
        run: |
          python3 examples/data_preprocess/gsm8k.py
      - name: Running GRPO gsm8k e2e training tests with FSDP on 2 L20 GPUs (Qwen)
        run: |
          ray stop --force
          bash tests/e2e/run_qwen_grpo.sh
  e2e_grpo_gsm8k_deepseek_coder:
    # NOTE: No need to just change model if the previous job fails
    needs: e2e_grpo_gsm8k_qwen
    runs-on: [L20x2]
    timeout-minutes: 40 # Increase this timeout value as needed
    env:
      HTTP_PROXY: ${{ secrets.PROXY_HTTP }}
      HTTPS_PROXY: ${{ secrets.PROXY_HTTPS }}
      NO_PROXY: "localhost,127.0.0.1"
      VLLM_ATTENTION_BACKEND: XFORMERS # TODO: Remove after update vllm in container
    container:
      image: whatcanyousee/verl:vemlp-th2.4.0-cu124-vllm0.6.3-ray2.10-te2.0-megatron0.11.0-v0.0.6
      options: --gpus 2 --shm-size=10g
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
            fetch-depth: 0
      - name: Install the current repository
        run: |
          pip3 install .[test]
      - name: Prepare gsm8k dataset
        run: |
          python3 examples/data_preprocess/gsm8k.py
      - name: Running GRPO gsm8k e2e training tests with FSDP on 2 L20 GPUs (DeepSeek)
        run: |
          ray stop --force
          bash tests/e2e/run_deepseek_grpo.sh