name: vllm

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
    paths:
      - "**/*.py"
      - .github/workflows/vllm.yml
  pull_request:
    branches:
      - main
    paths:
      - "**/*.py"
      - .github/workflows/vllm.yml

jobs:
  vllm:
    runs-on: [self-hosted, l20-1]
    container:
      image: verlai/verl:vemlp-th2.4.0-cu124-vllm0.6.3-ray2.10-te1.7-v0.0.3
      options: --gpus all --shm-size=10g
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
            fetch-depth: 0
      # - name: Activate conda environment
      #   run: |
      #     source ~/miniconda3/bin/activate
      #     conda activate ci
      - name: Install the current repository
        run: |
          pip3 install -e .
      - name: Running vllm tests on 8 L20 GPUs
        run: |
          cd tests/rollout
          pytest -s -x test_vllm_hf_loader.py
