# Usage Example:
# cd scripts/github_actions_runner
# export REPOSITORY=volcengine/verl
# export REG_TOKEN=...
# export RUNNER_NAME_STEM=verl-L20-$(hostname)
# export RUNNER_LABELS="L20x2"
# docker compose up --scale runner=4
services:
  runner:
    build:
      context: .
      dockerfile: Dockerfile.github.actions.runner
    restart: unless-stopped
    environment:
      - REPOSITORY=${REPOSITORY:-"volcengine/verl"}
      - REG_TOKEN=${REG_TOKEN:-""}
      - RUNNER_NAME=${RUNNER_NAME_STEM-"verl-$(hostname)"}-{{.Task.Slot}}
      - RUNNER_LABELS=${RUNNER_LABELS:-""}
      - RUNNER_GROUP=${RUNNER_GROUP:-"default"}
      - RUNNER_WORK_DIR=${RUNNER_WORK_DIR:-"_work"}
    deploy:
      resources:
        reservations:
          cpus: ${CPU_RESERVATIONS_PER_REPLICA:-40}
          memory: ${MEMORY_RESERVATIONS_PER_REPLICA:-180G}
          devices:
            # c.f. https://docs.docker.com/compose/how-tos/gpu-support/
            - capabilities: [ gpu ]
              count: ${GPUS_PER_REPLICA:-2}
              driver: nvidia
    runtime: nvidia
    volumes:
      # Mount Docker socket for Docker-in-Docker
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount runner's working directory for persistence, with unique path per replica
      - ${RUNNER_WORK_HOME:-${HOME}/github-actions-runner/work-dirs}/replica-{{.Task.Slot}}:/home/docker/actions-runner/_work
